"""
SUANR_V2 Core Algorithm v1.0

Stochastic Uncertainty-Aware Neural Regression with empirical percentile
intervals.

Author: Martin Pitre
Project: SUANR_V2
Status: Core algorithm only — no embedded dataset, validation test, reporting,
or file-output routines.

Scientific boundary
-------------------
The percentile interval produced by this version describes the dispersion of
predictions generated by stochastic input perturbations. It must not be called
a calibrated prediction interval unless a separate calibration procedure has
verified its empirical coverage.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

import numpy as np
from numpy.typing import ArrayLike, NDArray
from scipy.stats import entropy
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.utils.validation import check_is_fitted


FloatArray = NDArray[np.float64]


@dataclass(frozen=True)
class SUANRPrediction:
    """Prediction results for one or more observations."""

    mean: FloatArray
    uncertainty_std: FloatArray
    entropy: FloatArray
    lower_bound: FloatArray
    upper_bound: FloatArray
    interval_width: FloatArray


class SUANR_V2:
    """
    Neural regression model with stochastic uncertainty estimates and
    empirical percentile bounds.

    The model first standardizes the input features and trains an
    ``MLPRegressor``. During prediction, it repeatedly perturbs the standardized
    inputs with Gaussian noise, obtains multiple forward predictions, and
    summarizes their distribution.

    Parameters
    ----------
    hidden_layer_sizes:
        Hidden-layer architecture passed to ``MLPRegressor``.
    stochastic_noise:
        Standard deviation of Gaussian noise added to standardized inputs.
    n_samples:
        Number of stochastic forward-prediction samples.
    lower_percentile, upper_percentile:
        Percentiles used as the empirical interval bounds.
    entropy_bins:
        Number of histogram bins used for prediction-distribution entropy.
    random_state:
        Seed used for model fitting and deterministic stochastic sampling.
    max_iter:
        Maximum training iterations for ``MLPRegressor``.
    """

    def __init__(
        self,
        hidden_layer_sizes: tuple[int, ...] = (64, 32),
        stochastic_noise: float = 0.05,
        n_samples: int = 50,
        lower_percentile: float = 5.0,
        upper_percentile: float = 95.0,
        entropy_bins: int = 10,
        random_state: int | None = 42,
        max_iter: int = 2000,
    ) -> None:
        self.hidden_layer_sizes = hidden_layer_sizes
        self.stochastic_noise = stochastic_noise
        self.n_samples = n_samples
        self.lower_percentile = lower_percentile
        self.upper_percentile = upper_percentile
        self.entropy_bins = entropy_bins
        self.random_state = random_state
        self.max_iter = max_iter

        self._validate_parameters()

        self.scaler = StandardScaler()
        self.model = MLPRegressor(
            hidden_layer_sizes=self.hidden_layer_sizes,
            activation="relu",
            solver="adam",
            random_state=self.random_state,
            max_iter=self.max_iter,
        )

    @property
    def nominal_interval_coverage(self) -> float:
        """Return the percentile span as a proportion, not a calibration claim."""
        return (self.upper_percentile - self.lower_percentile) / 100.0

    def fit(self, X: ArrayLike, y: ArrayLike) -> "SUANR_V2":
        """Fit the input scaler and neural regression model."""
        X_array = self._as_2d_float_array(X, name="X")
        y_array = np.asarray(y, dtype=float)

        if y_array.ndim != 1:
            raise ValueError("y must be a one-dimensional target array.")
        if X_array.shape[0] != y_array.shape[0]:
            raise ValueError("X and y must contain the same number of observations.")
        if not np.all(np.isfinite(y_array)):
            raise ValueError("y contains NaN or infinite values.")

        X_scaled = self.scaler.fit_transform(X_array)
        self.model.fit(X_scaled, y_array)
        self.n_features_in_ = X_array.shape[1]
        return self

    def collect_stochastic_predictions(self, X: ArrayLike) -> FloatArray:
        """
        Generate stochastic predictions.

        Returns
        -------
        numpy.ndarray
            Array with shape ``(n_samples, n_observations)``.
        """
        self._check_fitted()
        X_array = self._validate_prediction_input(X)
        X_scaled = self.scaler.transform(X_array)
        rng = np.random.default_rng(self.random_state)

        samples = np.empty((self.n_samples, X_scaled.shape[0]), dtype=float)
        for sample_index in range(self.n_samples):
            noise = rng.normal(0.0, self.stochastic_noise, X_scaled.shape)
            samples[sample_index] = self.model.predict(X_scaled + noise)

        return samples

    def predict(self, X: ArrayLike) -> SUANRPrediction:
        """Return mean predictions, uncertainty measures, and percentile bounds."""
        samples = self.collect_stochastic_predictions(X)

        mean = np.mean(samples, axis=0)
        uncertainty_std = np.std(samples, axis=0)
        entropy_values = self._histogram_entropy(samples)
        lower_bound = np.percentile(samples, self.lower_percentile, axis=0)
        upper_bound = np.percentile(samples, self.upper_percentile, axis=0)

        return SUANRPrediction(
            mean=np.asarray(mean, dtype=float),
            uncertainty_std=np.asarray(uncertainty_std, dtype=float),
            entropy=np.asarray(entropy_values, dtype=float),
            lower_bound=np.asarray(lower_bound, dtype=float),
            upper_bound=np.asarray(upper_bound, dtype=float),
            interval_width=np.asarray(upper_bound - lower_bound, dtype=float),
        )

    def predict_mean(self, X: ArrayLike) -> FloatArray:
        """Return only the stochastic mean prediction."""
        return self.predict(X).mean

    def _histogram_entropy(self, predictions: FloatArray) -> FloatArray:
        values = np.empty(predictions.shape[1], dtype=float)

        for observation_index in range(predictions.shape[1]):
            histogram, _ = np.histogram(
                predictions[:, observation_index],
                bins=self.entropy_bins,
                density=True,
            )
            values[observation_index] = float(entropy(histogram + 1e-10))

        return values

    def _validate_parameters(self) -> None:
        if not self.hidden_layer_sizes or any(size <= 0 for size in self.hidden_layer_sizes):
            raise ValueError("hidden_layer_sizes must contain positive integers.")
        if self.stochastic_noise < 0:
            raise ValueError("stochastic_noise must be non-negative.")
        if self.n_samples < 2:
            raise ValueError("n_samples must be at least 2.")
        if not 0.0 <= self.lower_percentile < self.upper_percentile <= 100.0:
            raise ValueError(
                "Percentiles must satisfy 0 <= lower_percentile < "
                "upper_percentile <= 100."
            )
        if self.entropy_bins < 2:
            raise ValueError("entropy_bins must be at least 2.")
        if self.max_iter <= 0:
            raise ValueError("max_iter must be positive.")

    def _check_fitted(self) -> None:
        check_is_fitted(self.scaler)
        check_is_fitted(self.model)
        if not hasattr(self, "n_features_in_"):
            raise RuntimeError("The SUANR_V2 model has not been fitted.")

    def _validate_prediction_input(self, X: ArrayLike) -> FloatArray:
        X_array = self._as_2d_float_array(X, name="X")
        if X_array.shape[1] != self.n_features_in_:
            raise ValueError(
                f"X has {X_array.shape[1]} features, but the fitted model expects "
                f"{self.n_features_in_}."
            )
        return X_array

    @staticmethod
    def _as_2d_float_array(X: ArrayLike, name: str) -> FloatArray:
        array = np.asarray(X, dtype=float)
        if array.ndim == 1:
            array = array.reshape(1, -1)
        if array.ndim != 2:
            raise ValueError(f"{name} must be a one- or two-dimensional array.")
        if array.shape[0] == 0 or array.shape[1] == 0:
            raise ValueError(f"{name} must not be empty.")
        if not np.all(np.isfinite(array)):
            raise ValueError(f"{name} contains NaN or infinite values.")
        return np.asarray(array, dtype=float)


__all__: Iterable[str] = ("SUANR_V2", "SUANRPrediction")
